### ISSUE TITLE
'React/RCTBridge.h' file not found

### ISSUE THREAD

**Issue by nhunghuynhthihong** [RobertSasak/react-native-openalpr#32]
After I linked openalpr to my xcode project, but it cannot run successfully:

<img width="809" alt="screen shot 2018-03-23 at 2 00 25 pm" src="https://user-images.githubusercontent.com/8254346/37815722-97291182-2ea2-11e8-802e-f79b72cb88c0.png">

<img width="994" alt="screen shot 2018-03-23 at 2 01 24 pm" src="https://user-images.githubusercontent.com/8254346/37815758-c7c911c0-2ea2-11e8-8b77-5be401e048cf.png">

And my pod file:

<img width="718" alt="screen shot 2018-03-23 at 1 57 42 pm" src="https://user-images.githubusercontent.com/8254346/37815634-3d73fb66-2ea2-11e8-9dcd-333a8716b2de.png">

Could you please help me on this?

**Comment by Sofianebenabdallah** [comment]
I have the same issue. I test this : 

In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).

Click on the 'Build' option at the left pane.

Uncheck 'Parallelize Build' under Build Options.

Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).

Clean the project and build.

But I still have the issue. Did you resolve it ?

Thank you

**Comment by puttputt** [comment]
Also having this issue

**Comment by RobertSasak** [comment]
Closing in favour of https://github.com/RobertSasak/react-native-openalpr/releases/tag/v2.0.1
